project:
  type: website

website:
  title: "dvirlar-quarto-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: 
        - yeti
      dark: 
        - yeti
        - dark-theme.scss
   # css: styles.css
    toc: true



