project:
  type: website
  output-dir: docs
  # output directory automatically set to "_site" folder
  # changing output directory to docs so that gh-pages works

website:
  #title: "DVK"
  navbar:
    pinned: true
    # pinned navbar keeps navbar at top of page
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      #- href: development.qmd
      #  text: Development
      - href: projects.qmd
        text: Projects
      - href: quick-tips.qmd
        text: Quick Tips
      #- href: resources.qmd
      #  text: Resources
    right: 
      - icon: github
        href: https://github.com/dvirlar2
      - icon: twitter
        href: https://twitter.com/dvirlar2
        
  page-footer:
    left: "<i>Copyright 2022, Daphne Virlar-Knight</i>"
    right: 
      - icon: github
        href: https://github.com/dvirlar2
      - icon: twitter
        href: https://twitter.com/dvirlar2
   # center: "Site built with Quarto, GitHub, and a whole lot of trial and error"
   # can't figure out the vertical alignment.
    background: $primary
  
format:
  html:
    theme: 
      light: 
        - yeti
        - styles.scss
      dark: 
        - yeti
        - dark-theme.scss
   # css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github #mokokai



