---
title: "Graphing Colorado's Predicted Snowfall, 2020-2080."

description: |
  Using open climate data from University of Colorado Boulder, I created a time series plot of predicted snowfall during ski seasons between 2020-2080. The graph illustrates predicted snowfall for three separate climate ensembles.

date: last-modified
date-format: MMMM D, YYYY

categories: time series

execute:
  freeze: auto  # re-render only when source changes
---

------------------------------------------------------------------------

This is an example of a time series graph I created using publicly accessible 
data from the Community Earth System Model (CESM) at the University Corporation
for Atmospheric Research (UCAR). These graphs were created as part of a graduate-level
course on Climate Change Impacts and Adaptation (Spring 2020), taught by [Prof. Samantha Stevenson](https://bren.ucsb.edu/people/samantha-stevenson).



```{r}
#| warning: false
#| echo: false

# load source script
source(here::here("_data", "colorado-predicted-snowfall",'colorado-predicted-snowfall-script.R'))
```

```{r}
#| echo: false

wrap_plots(en_01_graph / en_02_graph / en_03_graph)
```



